version: "3.8"
services:
  nim-app:
    networks:
      - nim-network
    build: .
    tty: true
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "80:8080" # 必要に応じてポートを変更してください

  db:
    container_name: db
    image: mysql:5.7
    networks:
      - nim-network
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb:

networks:
  nim-network:
    driver: bridge
